import type { Metadata } from "next";
import {
  Bars3Icon,
  CheckBadgeIcon,
  EnvelopeIcon,
} from "@heroicons/react/24/outline";
import { Inter } from "next/font/google";
import Image from "next/image";
import Link from "next/link";
import "./globals.css";

const font = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <div className="grid lg:w-[80vw] lg:border-x lg:dark:border-white/20 lg:mx-auto md:grid-cols-[minmax(min-content,25%),1fr] grid-cols-1">
          <div className="hidden md:block border-r dark:border-white/20">
            <ul className="grid grid-cols-1">
              {Array(7)
                .fill({})
                .map((_, index) => (
                  <li
                    key={index}
                    className="px-4 py-6 grid grid-cols-[theme(spacing[12]),1fr] items-center gap-x-4 border-b dark:border-white/20"
                  >
                    <div className="size-12 bg-gray-950/10 dark:bg-white/10 animate-pulse rounded-full" />
                    <div className="space-y-2 w-full">
                      <div className="h-4 w-[95%] bg-gray-950/10 dark:bg-white/10 animate-pulse rounded-md" />
                      <div className="h-4 w-[70%] bg-gray-950/10 dark:bg-white/10 animate-pulse rounded-md" />
                    </div>
                  </li>
                ))}
            </ul>
          </div>
          <div className="grid h-full min-h-svh relative grid-rows-[theme(spacing[16]),1fr]">
            <header className="z-10 bg-background sticky top-0 gap-x-4 px-6 py-3 grid grid-rows-1 grid-cols-[theme(spacing[6]),1fr,theme(spacing[6])] content-center border-b dark:border-white/20">
              <button>
                <Bars3Icon className="size-6 stroke-2" />
              </button>
              <div className="flex items-center gap-x-3">
                <Image
                  src="https://github.com/raiyansarker.png"
                  alt="Raiyan"
                  width={200}
                  height={200}
                  className="size-11 rounded-full"
                />
                <div className="space-y-1">
                  <h1 className="flex items-center gap-x-2 leading-none font-semibold text-lg">
                    Raiyan Sarker
                    <span>
                      <CheckBadgeIcon className="size-5" />
                    </span>
                  </h1>
                  <p className="leading-none text-sm text-gray-950/70 dark:text-white/50">
                    Online
                  </p>
                </div>
              </div>
              <Link
                href="/contact"
                className="inline-grid place-items-center"
                title="Contact Me"
              >
                <span className="sr-only">Go to contact page</span>
                <EnvelopeIcon className="size-6 stroke-2" />
              </Link>
            </header>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
